name: 🔒 Weekly Dependency Audit

on:
  schedule:
    - cron: '0 0 * * 0' # Every Sunday at midnight UTC
  workflow_dispatch:
  push:
    branches: [main, dev]

permissions:
  contents: read
  issues: write

jobs:
  audit:
    name: 🔎 pnpm Audit Security Check
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18.x

      - name: Setup pnpm
        uses: pnpm/action-setup@v2
        with:
          version: 8

      - name: Install Dependencies
        run: pnpm install

      - name: Run Audit and Save Report
        run: |
          pnpm audit --json > audit-report.json || true
          jq -r '.advisories[]?.title' audit-report.json || echo "✅ No vulnerabilities found."

      - name: Create GitHub Security Issue (if vulnerabilities found)
        if: always()
        uses: actions/github-script@v7
        with:
          script: |
            const fs = require('fs');
            const data = JSON.parse(fs.readFileSync('audit-report.json', 'utf8'));
            const advisories = data.advisories || {};
            const keys = Object.keys(advisories);

            if (keys.length === 0) {
              console.log("✅ No advisories to report.");
              return;
            }

            const body = keys.map(id => {
              const adv = advisories[id];
              return `- [${adv.module_name}](${adv.url}) — ${adv.title} (Severity: ${adv.severity})`;
            }).join("\n");

            const title = `🚨 Security Alert: ${keys.length} vulnerabilities detected via pnpm audit`;

            const issues = await github.rest.issues.listForRepo({
              owner: context.repo.owner,
              repo: context.repo.repo,
              labels: "🔒 security",
              state: "open"
            });

            const alreadyOpen = issues.data.find(issue =>
              issue.title.includes("Security Alert") &&
              issue.user.login === "github-actions[bot]"
            );

            if (alreadyOpen) {
              console.log("⚠️ Existing security alert already open.");
              return;
            }

            await github.rest.issues.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title,
              body: `The following vulnerabilities were found in \`pnpm audit\`:\n\n${body}`,
              labels: ["🔒 security", "🤖 automation"]
            });
